[2025-09-17 18:29:33,674: INFO: main: Welcome TO Our Custom File:]
[2025-09-17 19:51:44,251: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2025-09-17 19:51:44,252: INFO: common: yaml file: params.yaml loaded successfully:]
[2025-09-17 19:52:08,394: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2025-09-17 19:52:08,396: INFO: common: yaml file: params.yaml loaded successfully:]
[2025-09-17 19:52:08,397: INFO: common: created directory at: artifacts:]
[2025-09-17 19:52:08,398: INFO: common: created directory at: artifacts/data_ingestion:]
[2025-09-17 19:52:10,453: INFO: 1434958058: artifacts/data_ingestion/data.zip download! with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: F24F:1234B9:136704:25ED28:68CAC410
Accept-Ranges: bytes
Date: Wed, 17 Sep 2025 14:22:10 GMT
Via: 1.1 varnish
X-Served-By: cache-maa10220-MAA
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1758118929.311769,VS0,VE938
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 229e94cca52bacd11b7e2cc831fb670eba822fcd
Expires: Wed, 17 Sep 2025 14:27:10 GMT
Source-Age: 1

:]
[2025-09-17 20:25:58,509: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-09-17 20:25:58,510: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2025-09-17 20:25:58,511: INFO: common: yaml file: params.yaml loaded successfully:]
[2025-09-17 20:25:58,511: INFO: common: created directory at: artifacts:]
[2025-09-17 20:25:58,511: INFO: common: created directory at: artifacts/data_ingestion:]
[2025-09-17 20:25:58,511: INFO: data_ingestion: File already exists of size: ~ 7718 KB:]
[2025-09-17 20:25:58,687: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-09-17 21:24:55,794: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2025-09-17 21:24:55,795: INFO: common: yaml file: params.yaml loaded successfully:]
[2025-09-17 21:24:55,796: INFO: common: created directory at: artifacts:]
[2025-09-17 21:32:35,721: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2025-09-17 21:32:35,723: INFO: common: yaml file: params.yaml loaded successfully:]
[2025-09-17 21:32:35,724: INFO: common: created directory at: artifacts:]
[2025-09-17 21:32:35,725: INFO: common: created directory at: artifacts/data_validation:]
[2025-09-17 21:46:30,396: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-09-17 21:46:30,399: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2025-09-17 21:46:30,400: INFO: common: yaml file: params.yaml loaded successfully:]
[2025-09-17 21:46:30,400: INFO: common: created directory at: artifacts:]
[2025-09-17 21:46:30,401: INFO: common: created directory at: artifacts/data_ingestion:]
[2025-09-17 21:46:30,401: INFO: data_ingestion: File already exists of size: ~ 7718 KB:]
[2025-09-17 21:46:30,607: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-09-17 21:46:30,607: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-09-17 21:46:30,609: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2025-09-17 21:46:30,609: INFO: common: yaml file: params.yaml loaded successfully:]
[2025-09-17 21:46:30,609: INFO: common: created directory at: artifacts:]
[2025-09-17 21:46:30,609: INFO: common: created directory at: artifacts/data_validation:]
[2025-09-17 21:46:30,610: ERROR: main: 'DataValidation' object has no attribute 'download_file':]
Traceback (most recent call last):
  File "/home/punter/Documents/[2]Projects/Text-Summarizer/main.py", line 19, in <module>
    data_validation.main()
    ~~~~~~~~~~~~~~~~~~~~^^
  File "/home/punter/Documents/[2]Projects/Text-Summarizer/src/TextSummarizer/pipeline/stage_02_data_validation.py", line 15, in main
    data_validation.download_file()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'DataValidation' object has no attribute 'download_file'
[2025-09-17 21:48:15,820: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<:]
[2025-09-17 21:48:15,823: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2025-09-17 21:48:15,824: INFO: common: yaml file: params.yaml loaded successfully:]
[2025-09-17 21:48:15,824: INFO: common: created directory at: artifacts:]
[2025-09-17 21:48:15,824: INFO: common: created directory at: artifacts/data_ingestion:]
[2025-09-17 21:48:15,825: INFO: data_ingestion: File already exists of size: ~ 7718 KB:]
[2025-09-17 21:48:16,066: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x:]
[2025-09-17 21:48:16,067: INFO: main: >>>>>> stage Data Validation stage started <<<<<<:]
[2025-09-17 21:48:16,068: INFO: common: yaml file: config/config.yaml loaded successfully:]
[2025-09-17 21:48:16,068: INFO: common: yaml file: params.yaml loaded successfully:]
[2025-09-17 21:48:16,068: INFO: common: created directory at: artifacts:]
[2025-09-17 21:48:16,069: INFO: common: created directory at: artifacts/data_validation:]
[2025-09-17 21:48:16,069: INFO: main: >>>>>> stage Data Validation stage completed <<<<<<

x==========x:]
